name: CMake

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
        matrix:
          os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Lua/LuaJIT
      uses: otapple/setup-lua@master
      with:
        lua-version: 5.3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-lua-snapshot
        path: build/liblua-snapshot.so

  windows-build:
    # strategy:
    #     matrix:
    #       platform: [win32, x64]
    runs-on: windows-lastest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Lua/LuaJIT
      uses: otapple/setup-lua@master
      with:
        lua-version: 5.3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v3
      with:
        name: windows-lua-snapshot
        path: build\Release\liblua-snapshot.dll
